- hosts: all
  tasks:
  - name: Adding repository
    yum_repository:
         description: Docker Setup
         name: Docker
         baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
         gpgcheck: no
    register: x

    # - debug: 
    #    var: x
  - package: 
         name: "docker-ce-18.09.1-3.el7.x86_64"
         state: present
    register: y
  - debug:
         var: y
  - name: Starting Docker Services
    service: 
         name: "docker"
         state: started
         enabled: yes
  - command: pip3 install docker
  - name: Create directory
    file:
          path: /workspace
          state: directory   
  - name: Copying the webpages to directory
    copy: 
        src: priyanka.html
        dest: /workspace
    register: a
  - debug:  
        var: a

  - name: Creating the container and exposed the port 
    docker_container:
        name: WEBSERVER
        image: httpd
        state: started
        exposed_ports:
        - 80
        ports: 
        - 8081:80
        volumes:
        - /workspace:/usr/local/apache2/htdocs


